\connect movs_app_db

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO brigitte;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(30) NOT NULL,
  CONSTRAINT pk_roles PRIMARY KEY (id),
  CONSTRAINT uk_roles_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(120) NOT NULL,
  correo VARCHAR(160) NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  rol_id BIGINT NOT NULL,
  CONSTRAINT pk_usuarios PRIMARY KEY (id),
  CONSTRAINT uk_usuarios_correo UNIQUE (correo),
  CONSTRAINT fk_usuarios_roles FOREIGN KEY (rol_id) REFERENCES roles(id)
);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios (rol_id);

CREATE TABLE IF NOT EXISTS planes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(80) NOT NULL,
  precio NUMERIC(10,2) NOT NULL,
  duracion_dias INTEGER NOT NULL,
  CONSTRAINT pk_planes PRIMARY KEY (id),
  CONSTRAINT uk_planes_codigo UNIQUE (codigo),
  CONSTRAINT uk_planes_nombre UNIQUE (nombre),
  CONSTRAINT chk_planes_precio CHECK (precio >= 0),
  CONSTRAINT chk_planes_duracion CHECK (duracion_dias > 0)
);

CREATE TABLE IF NOT EXISTS plan_beneficios (
  plan_id BIGINT NOT NULL,
  orden INTEGER NOT NULL,
  beneficio VARCHAR(180) NOT NULL,
  CONSTRAINT pk_plan_beneficios PRIMARY KEY (plan_id, orden),
  CONSTRAINT fk_beneficios_planes FOREIGN KEY (plan_id) REFERENCES planes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS suscripciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  usuario_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_expiracion DATE NOT NULL,
  estado VARCHAR(20) NOT NULL,
  CONSTRAINT pk_suscripciones PRIMARY KEY (id),
  CONSTRAINT uk_suscripciones_usuario UNIQUE (usuario_id),
  CONSTRAINT fk_suscripciones_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
  CONSTRAINT fk_suscripciones_planes FOREIGN KEY (plan_id) REFERENCES planes(id),
  CONSTRAINT chk_suscripciones_fechas CHECK (fecha_expiracion > fecha_inicio),
  CONSTRAINT chk_suscripciones_estado CHECK (estado IN ('ACTIVA','VENCIDA','CANCELADA'))
);
CREATE INDEX IF NOT EXISTS idx_suscripciones_plan ON suscripciones (plan_id);

CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(80) NOT NULL,
  CONSTRAINT pk_categorias PRIMARY KEY (id),
  CONSTRAINT uk_categorias_nombre UNIQUE (nombre)
);
CREATE INDEX IF NOT EXISTS idx_categorias_nombre ON categorias (nombre);

CREATE TABLE IF NOT EXISTS peliculas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  titulo VARCHAR(160) NOT NULL,
  anio INTEGER NOT NULL,
  genero VARCHAR(60) NOT NULL,
  descripcion VARCHAR(1000) NOT NULL,
  imagen_url VARCHAR(255) NOT NULL,
  variante VARCHAR(60),
  categoria_id BIGINT NOT NULL,
  CONSTRAINT pk_peliculas PRIMARY KEY (id),
  CONSTRAINT chk_peliculas_anio CHECK (anio BETWEEN 1888 AND 2100),
  CONSTRAINT fk_peliculas_categorias FOREIGN KEY (categoria_id) REFERENCES categorias(id)
);
CREATE INDEX IF NOT EXISTS idx_peliculas_titulo ON peliculas (titulo);
CREATE INDEX IF NOT EXISTS idx_peliculas_genero ON peliculas (genero);
CREATE INDEX IF NOT EXISTS idx_peliculas_categoria ON peliculas (categoria_id);

CREATE TABLE IF NOT EXISTS sesiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  usuario_id BIGINT NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_inicio TIMESTAMP(6) NOT NULL,
  fecha_cierre TIMESTAMP(6),
  CONSTRAINT pk_sesiones PRIMARY KEY (id),
  CONSTRAINT uk_sesiones_usuario UNIQUE (usuario_id),
  CONSTRAINT fk_sesiones_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sesiones_activa ON sesiones (activa);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO brigitte;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO brigitte;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO brigitte;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO brigitte;
